import type { BuiltinTheme } from "./types";

export const anvilLight: BuiltinTheme = {
  id: "builtin:anvil-light",
  name: "Anvil Light",
  description: "明亮环境。米白底，金铜强调。",
  variables: {
    "--bg-app": "#f5efe1",
    "--bg-panel": "#ece4d2",
    "--bg-surface": "#ffffff",
    "--bg-raised": "#e0d6c0",
    "--bg-overlay": "rgba(0, 0, 0, 0.3)",
    "--fg-primary": "#2a231a",
    "--fg-secondary": "#5a4d3d",
    "--fg-muted": "#8a7d6d",
    "--fg-inverse": "#f5efe1",
    "--accent-iron": "#6a6a6a",
    "--accent-steel": "#4a5560",
    "--accent-copper": "#a05a2c",
    "--accent-gold": "#b8964a",
    "--accent-ember": "#c8401f",
    "--accent-flame": "#d96b2a",
    "--border-subtle": "#ddd3bd",
    "--border-default": "#c8bca0",
    "--border-strong": "#a89880",
    "--border-accent": "#b8964a",
    "--danger": "#c8401f",
    "--success": "#4a7a3a",
    "--warning": "#b8964a",
    "--card-yugioh-outer-1": "#d4c5a0",
    "--card-yugioh-outer-2": "#b8a678",
    "--card-yugioh-outer-3": "#8f7d52",
    "--card-yugioh-inner-bg-1": "#f7efd6",
    "--card-yugioh-inner-bg-2": "#ede0bf",
    "--card-yugioh-parchment": "#fdfaee",
    "--card-yugioh-text": "#3a2a10",
    "--card-yugioh-text-dim": "#4a3a1a",
    "--card-yugioh-star": "#b8860b",
    "--card-yugioh-shadow": "0 2px 6px rgba(0, 0, 0, 0.15)",
    "--card-yugioh-shadow-selected": "0 4px 14px rgba(0, 0, 0, 0.25)",
    "--chat-bubble-bg": "#ffffff",
    "--chat-bubble-border": "#ddd3bd",
    "--chat-bubble-text": "#2a231a",
    "--chat-action-text": "#5a4d3d",
    "--chat-roll-bg": "#f0e8d4",
    "--chat-roll-border": "#c8bca0",
    "--chat-roll-accent": "#4a5560",
    "--chat-narration-bg": "#f5ecd8",
    "--chat-narration-border": "#b8964a",
    "--chat-narration-text": "#5a4d3d",
    "--chat-ooc-bg": "#e8e0d0",
    "--chat-ooc-text": "#5a4d3d",
    "--chat-whisper-bg": "#f0e8f5",
    "--chat-whisper-border": "#9a7ab4",
    "--chat-whisper-text": "#6a4a8a",
    "--chat-system-text": "#8a7d6d",
    "--chat-system-line": "#ddd3bd",
    "--chat-panel-bg": "#faf5ea",
  },
};
