import type { BuiltinTheme } from "./types";

export const highContrast: BuiltinTheme = {
  id: "builtin:high-contrast",
  name: "High Contrast",
  description: "无障碍。纯黑底，高亮文字，强边框。",
  variables: {
    "--bg-app": "#000000",
    "--bg-panel": "#0a0a0a",
    "--bg-surface": "#141414",
    "--bg-raised": "#1e1e1e",
    "--bg-overlay": "rgba(0, 0, 0, 0.7)",
    "--fg-primary": "#ffffff",
    "--fg-secondary": "#e0e0e0",
    "--fg-muted": "#a0a0a0",
    "--fg-inverse": "#000000",
    "--accent-iron": "#c0c0c0",
    "--accent-steel": "#00d4ff",
    "--accent-copper": "#ff8800",
    "--accent-gold": "#ffff00",
    "--accent-ember": "#ff4444",
    "--accent-flame": "#ff8800",
    "--border-subtle": "#404040",
    "--border-default": "#808080",
    "--border-strong": "#c0c0c0",
    "--border-accent": "#ffff00",
    "--danger": "#ff4444",
    "--success": "#44ff44",
    "--warning": "#ffff00",
    "--card-yugioh-outer-1": "#ffffff",
    "--card-yugioh-outer-2": "#e0e0e0",
    "--card-yugioh-outer-3": "#c0c0c0",
    "--card-yugioh-inner-bg-1": "#1a1a1a",
    "--card-yugioh-inner-bg-2": "#0a0a0a",
    "--card-yugioh-parchment": "#000000",
    "--card-yugioh-text": "#ffffff",
    "--card-yugioh-text-dim": "#e0e0e0",
    "--card-yugioh-star": "#ffff00",
    "--card-yugioh-shadow": "0 0 0 2px #ffffff",
    "--card-yugioh-shadow-selected": "0 0 0 4px #ffff00",
    "--chat-bubble-bg": "#141414",
    "--chat-bubble-border": "#808080",
    "--chat-bubble-text": "#ffffff",
    "--chat-action-text": "#e0e0e0",
    "--chat-roll-bg": "#0a0a0a",
    "--chat-roll-border": "#808080",
    "--chat-roll-accent": "#00d4ff",
    "--chat-narration-bg": "#0a0a0a",
    "--chat-narration-border": "#ffff00",
    "--chat-narration-text": "#ffffff",
    "--chat-ooc-bg": "#1a1a1a",
    "--chat-ooc-text": "#e0e0e0",
    "--chat-whisper-bg": "#1a0a1a",
    "--chat-whisper-border": "#c0c0ff",
    "--chat-whisper-text": "#c0c0ff",
    "--chat-system-text": "#a0a0a0",
    "--chat-system-line": "#404040",
    "--chat-panel-bg": "#000000",
  },
};
